//
// Created by Christian Curry on 2/23/16.
//

#ifndef EMULATE6502_ADDRESSINGMODES_H
#define EMULATE6502_ADDRESSINGMODES_H

enum AddressingMode {
    NULL_ADDRESSING_MODE,
    RELATIVE,
    ACCUMULATOR,
    IMPLIED,
    IMMEDIATE,
    ZERO_PAGE,
    ZERO_PAGEX,
    ZERO_PAGEY,
    ABSOLUTE,
    ABSOLUTEX,
    ABSOLUTEY,
    INDIRECT, //ONLY USED BY JMP INSTRUCTION
    INDEXED_INDIRECTX,
    INDIRECT_INDEXEDY
};

#endif //EMULATE6502_ADDRESSINGMODES_H
